#!/bin/sh
export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus

eval "$(dbus-launch --sh-syntax --exit-with-session)"
[[ -f $MYXPATH/Xresources ]] && xrdb -merge $MYXPATH/Xresources
# [[ -f $MYXPATH/Xresources ]] && xmodmap $MYXPATH/Xmodmap
sxhkd&
exec bspwm
