#!/bin/sh
# start the D-Bus session bus before Fcitx starts
export XMODIFIERS="@im=fcitx"
export QT_IM_MODULE=fcitx
export GTK_IM_MODULE=fcitx

# x env
export _JAVA_AWT_WM_NONREPARENTING=1
export EDITOR="emacs"
export TERMINAL="alacritty"
export BROWSER="firefox"

eval "$(dbus-launch --sh-syntax --exit-with-session)"
[[ -f $MYXPATH/Xresources ]] && xrdb -merge $MYXPATH/Xresources
sxhkd&
exec bspwm
