#!/bin/bash

wpPath=$HOME/Pictures/wallpapers

while getopts :aof: opts; do
    case $opts in
        a) picPath=$wpPath/alena ;;
        o) picPath=$wpPath/other ;;
        f) picPath=$wpPath/$OPTARG ;;
        ?) echo "invalid option";;
    esac
done

picName=$(ls ${picPath} | sort -R | head -n1)
PIC=$picPath/$picName

notify-send "change wallpapers: $picName"

wal -i $PIC
