#!/bin/bash

wpPath=$HOME/Pictures/wallpapers

while getopts :aof: opts; do
    case $opts in
        a) picPath=$wpPath/alena ;;
        o) picPath=$wpPath/other ;;
        f) picPath=$wpPath/$OPTARG ;;
        ?) echo "invalid option";;
    esac
done


PIC=$picPath/$(ls ${picPath} | sort -R | head -n1)
echo $PIC

wal -i $PIC
