#!/bin/bash

bash ${HOME}/.config/bspwm/autostart.sh

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config active_border_color "$color2"
bspc config focused_border_color "$color2"
bspc config presel_feedback_color "$color1"


bspc config border_width            3
bspc config window_gap              15
bspc config top_padding             34
bspc config split_ratio             0.52

bspc config focus_follows_pointer   false
bspc config borderless_monocle      true
bspc config gapless_monocle         false
bspc config single_monocle          true

bspc rule -a Firefox        desktop='^2' follow=on
bspc rule -a discord        desktop='^4'
bspc rule -a mpv            desktop='^4' follow=on
bspc rule -a feh            state=floating follow=on
bspc rule -a Tilda          state=floating floating=on focus=on sticky=on border=off
bspc rule -a Demo           state=floating floating=on focus=on sticky=on

# bspc monitor eDP1 -d TERM WEB CODE FILES MEDIA EXTRA COMMUNI READ
bspc monitor eDP1 -d TERM WEB CODE MEDIA FILES

# wmname LG3D
