#!/bin/bash

focused=$(xrdb ~/.myprofile/config/X11/xresources -query all | grep color7 | cut -f2)
normal=$(xrdb ~/.myprofile/config/X11/xresources -query all | grep color8 | cut -f2)

bspc config focused_border_color    "$focused"
bspc config normal_border_color     "$normal"
bspc config border_width            3
bspc config window_gap              15
bspc config top_padding             34
bspc config split_ratio             0.52

bspc config focus_follows_pointer   false
bspc config borderless_monocle      true
bspc config gapless_monocle         false
bspc config single_monocle          true

bspc rule -a Nightly    desktop='^2' follow=on
bspc rule -a mpv        desktop='^5' state=fullscreen follow=on
bspc rule -a feh        state=fullscreen follow=on
bspc rule -a Tilda      state=floating floating=on focus=on sticky=on
bspc rule -a tilda      state=floating floating=on focus=on sticky=on

bspc monitor eDP-1 -d TERM WEB CODE COMMUNI FILES READ EXTRA MEDIA

sh $HOME/.config/polybar/launch.sh
