#!/bin/bash

bash ${HOME}/.config/bspwm/autostart.sh

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config active_border_color "$color2"
bspc config focused_border_color "$color2"
bspc config presel_feedback_color "$color1"


bspc config border_width            3
bspc config window_gap              15
bspc config top_padding             34
bspc config split_ratio             0.52

bspc config focus_follows_pointer   false
bspc config borderless_monocle      true
bspc config gapless_monocle         false
bspc config single_monocle          true

# bspc rule -a Google-chrome      desktop='^2' follow=on
bspc rule -a Code            	desktop='^7'
bspc rule -a Telegram           desktop='^7'
bspc rule -a discord            desktop='^7'
bspc rule -a Zathura 		state=tiled
bspc rule -a mpv                desktop='^5' state=floating follow=on
bspc rule -a feh                state=floating follow=on
bspc rule -a Tilda              state=floating floating=on focus=on sticky=on
bspc rule -a Demo               state=floating floating=on focus=on sticky=on
bspc rule -a Microbench         desktop='^3' state=floating floating=on focus=on sticky=on
bspc rule -a ShaderBench        desktop='^3' state=floating floating=on focus=on sticky=on

bspc monitor DisplayPort-0 -d TERM WEB CODE FILES
bspc monitor HDMI-A-0 -d MEDIA EXTRA COMMUNI READ

# wmname LG3D
