export PATH=/home/npchitman/.script/:$PATH
export PATH=~/.npm-global/bin:$PATH
export PATH=~/.local/appimage/:$PATH
export PATH=~/.local/bin/:$PATH
export SYSTEMD_EDITOR=vim
export SUDO_ASKPASS=~/.config/rofi/scripts/rofi-askpass

#######################################################

if [[ ! $DISPLAY && $XDG_VTNR -eq 1 ]]; then
  exec startx -- vt1 &> /dev/null
  exec wal -i /home/npchitman/Pictures/wallpapers/inspacenoonecanhearyouscream.jpg
fi

