
;███████╗███╗   ███╗ █████╗  ██████╗███████╗
;██╔════╝████╗ ████║██╔══██╗██╔════╝██╔════╝
;█████╗  ██╔████╔██║███████║██║     ███████╗
;██╔══╝  ██║╚██╔╝██║██╔══██║██║     ╚════██║
;███████╗██║ ╚═╝ ██║██║  ██║╚██████╗███████║
;╚══════╝╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝╚══════╝

;; ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
;; 基本配置
;; ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
(global-hl-line-mode t)
(show-paren-mode 1)
(require 'ibus)
(add-hook 'after-init-hook 'ibus-mode-on)
(ibus-mode t)
;; (fcitx-evil-turn-on)
(cnfonts-enable)

(setq cnfonts-use-face-font-rescale t)
(add-hook '-mode-hook #'rainbow-delimiters-mode)
;; ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
;; nyan-mode
;; ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
(use-package nyan-mode
  :init
    (setq nyan-animate-nyancat t)
    (setq nyan-wavy-trail t)
    (setq nyan-bar-length 15)
    (nyan-mode t)
  )
;; ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
;; csharp
;; ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
(use-package csharp-mode
  :ensure t
  :after company
  :config
  (use-package omnisharp
    :init
    (omnisharp-mode)
    :ensure t
    )
  (eval-after-load
      'company
    '(add-to-list 'company-backends #'company-omnisharp))
  (add-hook 'csharp-mode-hook #'flycheck-mode)
  (add-hook 'csharp-mode-hook #'company-mode)
  )

;; ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
;; org
;; ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
(setq org-startup-indented t)
(setq org-bullets-bullet-list '("◉" "○" "✸" "✿"))
(add-hook 'org-mode-hook #'org-bullets-mode)
 (setq org-todo-keywords
       '((sequence "TODO(t)" "INPROGRESS(i)" "WAITING(w)" "REVIEW(r)" "|" "DONE(d)" "CANCELED(c)")))
;; todo colors
(setf org-todo-keyword-faces '(("TODO" . (:foreground "white" :background "#95A5A6"   :weight bold))
                                ("HAND" . (:foreground "white" :background "#2E8B57"  :weight bold))
                                ("DONE" . (:foreground "white" :background "#3498DB" :weight bold))))

;; ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
;; lsp
;; ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
(setq ccls-exectuable "/usr/bin/ccls")
(eval-after-load 'lsp-mode
  '(progn
     ;; enable log only for debug
     (setq lsp-log-io nil)
     ;; use `evil-matchit' instead
     (setq lsp-enable-folding nil)
     ;; handle yasnippet by myself
     (setq lsp-enable-snippet t)
     ;; use `company-ctags' only.
     ;; Please `company-lsp' is automatically enabled if installed
     (setq lsp-enable-completion-at-point t)
     ;; turn off for better performance
     (setq lsp-enable-symbol-highlighting nil)
     ;; use ffip instead
     (setq lsp-enable-links nil)
     ;; don't scan 3rd party javascript libraries
     (push "[/\\\\]\\node_modules$" lsp-file-watch-ignored)))

(add-hook 'c++-mode-hook #'lsp)
;; ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
;; doom;;modeline
;; ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
(use-package doom-modeline
  :ensure t
  :hook (after-init . doom-modeline-mode)
  :init
    (setq doom-modeline-buffer-encoding nil)
    (setq doom-modeline-indent-info nil)
    (setq doom-modeline-lsp t)
    (setq doom-modeline-enable-word-count t)
    (setq doom-modeline-github t)
    (display-time-mode -1)
    (display-line-numbers-mode -1)
  )
;; ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
;; rainbow-delimiters-mode
;; ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
(use-package rainbow-delimiters
  :init
    (add-hook 'csharp-mode-hook #'rainbow-delimiters-mode)
    (add-hook 'c++-mode-hook #'rainbow-delimiters-mode)
    (add-hook 'c-mode-hook #'rainbow-delimiters-mode)
    (add-hook 'lisp-mode-hook #'rainbow-delimiters-mode)
    (add-hook 'python-mode-hook #'rainbow-delimiters-mode)
  )

;; ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
;; 
;; ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

;; ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
;;
;; ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
;; Auto generated by cnfonts
;; <https://github.com/tumashu/cnfonts>
