#!/bin/sh

MY_X11_PROFILE=$HOME/.myprofile/config/X11
userresources=$MY_X11_PROFILE/xresources
usermodmap=$MY_X11_PROFILE/xmodmap
userprofile=$MY_X11_PROFILE/xprofile
sysresources=/etc/X11/xinit/Xresources
sysmodmap=/etc/X11/xinit/Xmodmap
sysprofile=/etc/xprofile

# merge in defaults and keymaps

if [ -f $sysresources ]; then
  xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
  xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
	xrdb -load "$userresources"
fi

if [ -f "$usermodmap" ]; then
  xmodmap "$usermodmap"
fi

# start some nice programs

failsafe="yes"

for f in /etc/X11/xinit/xinitrc.d/?* ; do
  [ -x "$f" ] && . "$f"
done
unset f
#fi

if [ -n "$failsafe" ]; then
	[ -f $sysprofile ] && source $sysprofile
	[ -f $userprofile ] && source $userprofile
	exec bspwm
else
 exec $command
fi

