#!/bin/sh

export FONTCONFIG_PATH="/etc/fonts"
export EDITOR="nvim"
export PATH="$PATH:$MYPATH"
export TERMINAL="sakura"
export BROWSER="google-chrome-stable"

export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS="@im=fcitx"

eval "$(dbus-launch --sh-syntax --exit-with-session)"
xset +fp ~/.local/share/fonts
xset fp rehash
xsetroot -cursor_name left_ptr
xbacklight -set 40%
mpd &
sxhkd &
syndaemon -i 0.5 -t -K -R -d
bash "$HOME/.myprofile/config/X11/autostart.sh"
