#!/bin/sh

export FONTCONFIG_PATH="/etc/fonts"
export EDITOR="nvim"
export PATH="$PATH:$MYPATH"
export TERMINAL="sakura"
export BROWSER="google-chrome-stable"

export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS="@im=fcitx"
export _JAVA_AWT_WM_NONREPARENTING=1

eval "$(dbus-launch --sh-syntax --exit-with-session)"
xset +fp ~/.local/share/fonts
xset fp rehash
mpd &
sxhkd &
bash "$HOME/.myprofile/config/X11/autostart.sh"
